[[session]]
name = "󱘖 dotfiles"
path = "~/git/godinj-dotfiles/"
startup_command = "nvim"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "󰞵 deb-desk"
path = "~"
startup_command = "dd"
