[[session]]
name = " drem-ninja"
path = "~/git/drem-ninja/"
startup_command = "nvim"

[[session]]
name = " bib incr"
path = "~/git/BibleIncrementer"
startup_command = "nvim"

[[session]]
name = " bib incr use"
path = "~/git/BibIncrUse"
startup_command = "mvn exec:java"

[[session]]
name = " bib incr ion"
path = "~/git/BibleIncrementerIon"
startup_command = "nvim"

[[session]]
name = "󰇥 pything"
path = "~/pything/"
startup_command = "nvim"

[[session]]
name = "󰇥 ollama"
path = "~"
startup_command = "ollama ps"

[[session]]
name = "󰇥 ai-fundamentals-simple"
path = "~/git/ai-fundamentals-simple"

[[session]]
name = "󰇥 model comparison"
path = "~/experiments/models"
startup_command = "oc"

[[session]]
name = "󰇥 learning"
path = "~/experiments/learning"
startup_command = "oc"

[[session]]
name = " drem-soundscape"
path = "~/dev/drem-soundscape/"
startup_command = "nvim"

[[session]]
name = " juce editor"
path = "~/Documents/JUCE/"
startup_command = "nvim"

[[session]]
name = " drem-catalog"
path = "~/git/drem-catalog/"
startup_command = "nvim"

[[session]]
name = " drem-echo"
path = "~/git/drem-echo/"
startup_command = "nvim"

[[session]]
name = " golden-agents"
path = "~/git/golden-agents/"
startup_command = "nvim"

[[session]]
name = " drem-canvas"
path = "~/git/drem-canvas/"
startup_command = "cld"

[[session]]
name = " agent-notify"
path = "~/git/agent-notify/"
startup_command = "nvim"
