sort_order = [
    "tmux", # show first
    "tmuxinator",
    "config",
    "zoxide", # show last
]

[[session]]
name = "dotfiles"
path = "~/git/godinj-dotfiles/"
startup_command = "nvim"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "fastfetch"
path = "~"
startup_command = "fastfetch"

[[session]]
name = "btop"
path = "~"
startup_command = "btop"

[[session]]
name = "drem-soundscape"
path = "~/dev/drem-soundscape/"
startup_command = "nvim"
